-- 既存テーブルをすべて削除
DROP TABLE IF EXISTS reservationdetails CASCADE;
DROP TABLE IF EXISTS rentaldetails CASCADE;
DROP TABLE IF EXISTS reservations CASCADE;
DROP TABLE IF EXISTS rentals CASCADE;
DROP TABLE IF EXISTS reviews CASCADE;
DROP TABLE IF EXISTS books CASCADE;
DROP TABLE IF EXISTS users CASCADE;
DROP TABLE IF EXISTS categories CASCADE;
DROP TABLE IF EXISTS writers CASCADE;
DROP TABLE IF EXISTS announcements CASCADE;

-- ライター テーブル
CREATE TABLE writers(
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    writer_name VARCHAR(50),
    writer_description TEXT
);

-- カテゴリー テーブル
CREATE TABLE categories(
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    category_name VARCHAR(50)
);

-- ユーザー テーブル
CREATE TABLE users(
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email VARCHAR(255),
    name VARCHAR(20),
    password VARCHAR(50),
    tel_number VARCHAR(50),
    birthday VARCHAR(50),
    role VARCHAR(50)
);

-- 本 テーブル
CREATE TABLE books(
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title VARCHAR(50),
    writer_id INTEGER,
    publisher VARCHAR(50),
    summary TEXT,
    loans BOOLEAN,
    date DATE,
    category_id INTEGER,
    FOREIGN KEY (writer_id) REFERENCES writers(id),
    FOREIGN KEY (category_id) REFERENCES categories(id)
);

-- レビュー テーブル
CREATE TABLE reviews(
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    book_id INTEGER,
    book_review TEXT,
    FOREIGN KEY(book_id) REFERENCES books(id)
);

-- レンタル テーブル
CREATE TABLE rentals(
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id INTEGER,
    rental_date DATE,
    drop_date DATE,
    return_date DATE,
    FOREIGN KEY (user_id) REFERENCES users(id)
);

-- レンタル詳細 テーブル
CREATE TABLE rentaldetails(
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    rental_id INTEGER,
    book_id INTEGER,
    FOREIGN KEY (rental_id) REFERENCES rentals(id),
    FOREIGN KEY (book_id) REFERENCES books(id)
);

-- 予約 テーブル
CREATE TABLE reservations(
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id INTEGER,
    reservation_date DATE,
    FOREIGN KEY(user_id) REFERENCES users(id)
);

-- 予約詳細 テーブル（✅ スペルミス修正：resevationdetails → reservationdetails）
CREATE TABLE reservationdetails(
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    reservation_id INTEGER,
    book_id INTEGER,
    reservation_status BOOLEAN,
    FOREIGN KEY (reservation_id) REFERENCES reservations(id),
    FOREIGN KEY (book_id) REFERENCES books(id)
);

-- お知らせ テーブル
CREATE TABLE announcements(
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    content TEXT
);