package com.example.demo.entity;

import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.Table;

@Entity
@Table(name = "reservations")
public class Reservation {

	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	private Integer id; //予約ID
	
	private

	//	id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	//	user_id INTEGER,
	//	
	//	FOREIGN KEY(user_id) REFERENCES users(id)

}
