package com.example.demo.entity;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.Table;

@Entity
@Table(name = "reservationdetails")
public class Reservationdetail {

	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	private Integer id; //予約カートID

	@Column(name = "reservation_status")
	private Boolean reservationStatus; //t:貸し出し可 f:返却待ち

	//	id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	//	reservation_id INTEGER,
	//	book_id INTEGER,
	//	reservation_status BOOLEAN,
	//	
	//	FOREIGN KEY (reservation_id) REFERENCES reservations(id),
	//	FOREIGN KEY (book_id) REFERENCES books(id)
}
